# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4da661db02b26c81ed552f9a5894be0f083d60726875762b1cd4046f773557617f433c6adf0926e03c1c7d8d6353541b8a525d399e287a830e7f632e0815a006

test:
  secret_key_base: 640f31050310f4bd406a422e6c3a6f5d54152b03a5c5cc2104c8dd559e2650340c3d36008285213c6ff3187bd048f4cec6cb51d23f264ff82234bbe90cb55b39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
